{{- if ne .GetImageRepository "" }}
image:
  repository: {{ .GetImageRepository }}/devops-service-business
{{- end }}

{{- if ne .GetImageRepository "" }}
## 插件相关配置
plugins:
  # skywalking agent 镜像地址
  skywalkingAgentImage: {{ .GetImageRepository }}/skywalking-agent:6.6.0
{{- end }}

initDatabases:
  datasource:
    url: {{ .GetDatabaseUrl "" }}
    username: choerodon
    password: password
  datasources:
    # 多数据源初始化 初始化菜单数据
    platform:
      url: {{ .GetDatabaseUrl "" }}
      username: choerodon
      password: password
    message:
      url: {{ .GetDatabaseUrl "" }}
      username: choerodon
      password: password
extraEnv:
  SPRING_REDIS_HOST: {{ ( .GetResource "c7n-redis").Host }}
  SPRING_REDIS_PORT: {{ ( .GetResource "c7n-redis").Port }}
  SPRING_REDIS_DATABASE: 9
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: {{ .GetEurekaUrl }}
  SPRING_DATASOURCE_URL: {{ .GetDatabaseUrl "devops_service" }}
  SPRING_DATASOURCE_USERNAME: "choerodon"
  SPRING_DATASOURCE_PASSWORD: "password"
  SERVICES_GITLAB_URL: {{ .GetResourceDomainUrl "gitlab" }}
  SERVICES_GITLAB_SSHURL: {{ (.GetResource "gitlab").Domain }}:30022
  SERVICES_GITLAB_PROJECTLIMIT: 100
  SERVICES_HELM_URL: {{ .GetResourceDomainUrl "chartmuseum" }}
  SERVICES_HELM_USERNAME: {{ .GetReleaseValue "chartmuseum" "env.secret.BASIC_AUTH_USER" }}
  SERVICES_HELM_PASSWORD: {{ .GetReleaseValue "chartmuseum" "env.secret.BASIC_AUTH_PASS" }}
  SERVICES_HARBOR_BASEURL: {{ .GetResourceDomainUrl "harbor" }}
  SERVICES_HARBOR_USERNAME: admin
  SERVICES_HARBOR_PASSWORD: {{ .GetReleaseValue "harbor" "harborAdminPassword" }}
  SERVICES_HARBOR_INSECURESKIPTLSVERIFY: true
  SERVICES_GATEWAY_URL: {{ .GetResourceDomainUrl "choerodon-gateway" }}
  AGENT_VERSION: 2.0.2
  # 主机agent下载地址
  C7N_AGENT_BINARY_URL: https://file.choerodon.com.cn/choerodon-install/c7n-agent/2.0.0/c7n-agent-2.0.0-Linux-amd64.tar.gz
  # 主机agent版本
  C7N_AGENT_VERSION: 2.0.0
  AGENT_SERVICEURL: {{ .GetResourceDomainUrl "devops-service" }}/websocket
  AGENT_REPOURL: http://openchart.choerodon.com.cn/choerodon/c7n/
  AGENT_CERTMANAGERURL: http://openchart.choerodon.com.cn/choerodon/c7n/
  SERVICES_SONARQUBE_PASSWORD: password
  SERVICES_SONARQUBE_URL: {{ .GetResourceDomainUrl "sonarqube" }}
  SERVICES_SONARQUBE_USERNAME: admin
  DEVOPS_ANSIBLE_IMAGE: registry.cn-shanghai.aliyuncs.com/c7n/kubeadm-ha:0.1.3
  SONAR_FIX_IMAGE: registry.cn-shanghai.aliyuncs.com/c7n/sonar-scanner:4.6-jdk-11.0.11_9
ingress:
  enabled: true

