{{- if ne .GetImageRepository "" }}
image:
  repository: {{ .GetImageRepository }}/minio
mcImage:
   repository: {{ .GetImageRepository }}/mc
{{- end }}

mode: standalone
persistence:
  enabled: true
  storageClass: {{ .GetStorageClass }}
  size: 50Gi
ingress:
  enabled: true
