persistence:
  enabled: true
  storageClass: {{ .GetStorageClass }}
postgresql:
  enabled: true
  auth:
    password: "sonarqube_pw"
    username: bn_sonarqube
    database: bitnami_sonarqube
  primary:
    persistence:
      storageClass: {{ .GetStorageClass }}
      size: 50Gi
ingress:
  enabled: true
sonarqubePassword: "password"
sonarqubeUsername: admin

plugins:
  enabled: true
  commandOverride: |
    mkdir -p /bitnami/sonarqube/extensions/plugins && mkdir -p /opt/bitnami/sonarqube/data && chmod -R 777 /opt/bitnami/sonarqube/data